### ISSUE TITLE
Bug "Unsatisfiable !" pour `atmost(1,[a,b,c])` 

### ISSUE THREAD

**Issue by maelvalais** [FredMaris/touist#115]
Avec le `touistl` suivant : 
```
begin formula
exact(1,[a,b])
end formula
```
j'ai une exception bizarre lorsque j'appuie sur Solve. Pourtant, si je fais un truc qui est vraiment insatisfiable du genre `a and not a` alors j'obtiens bien le message "pas de solutions". 

Le log : 
```log
translate(): cmd executed: /Users/maelv/prog/touist/touist-gui/external/touistc -sat -table out.table -o out.cnf temp.touistl
launch(): cmd executed: java -jar external/minisat.jar /Users/maelv/prog/touist/touist-gui/out.cnf
Exception in thread "Thread-17" java.lang.NumberFormatException: For input string: "Unsatisfiable"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at solution.SolverTestSAT4J.parseModel(SolverTestSAT4J.java:179)
	at solution.SolverTestSAT4J.nextModel(SolverTestSAT4J.java:163)
	at solution.ModelListIterator.hasNext(ModelListIterator.java:59)
	at gui.editionView.ParentEditionPanel.initResultView(ParentEditionPanel.java:554)
	at gui.editionView.ParentEditionPanel.access$500(ParentEditionPanel.java:58)
	at gui.editionView.ParentEditionPanel$6.run(ParentEditionPanel.java:277)
	at java.lang.Thread.run(Thread.java:745)
```
---------
Voilà ce que devrait afficher l'interface si ce `atmost()` était vraiment insatisfiable : 
![capture d ecran 2016-03-13 a 00 10 43](https://cloud.githubusercontent.com/assets/2195781/13725884/2617548e-e8b0-11e5-9e5a-f780f952e95a.png)
```
translate(): cmd executed: /Users/maelv/prog/touist/touist-gui/external/touistc -sat -table out.table -o out.cnf temp.touistl
launch(): cmd executed: java -jar external/minisat.jar /Users/maelv/prog/touist/touist-gui/out.cnf
close(): solver has been closed correctly
hasNext(): there is no more models
This problem is unsatisfiable
```

**Comment by maelvalais** [comment]
Voilà un test rapide : 
```shell
$ echo "begin formula atmost(1,[a,b,c]) end formula" | ./external/touistc -sat -o /dev/stdout /dev/stdin
c CNF format file
p cnf 3 6
3 2 0
-3 0
-3 -1 0
-2 0
-2 -1 0
-2 -1 0
```
La table de correspondance est
```
&2 3
&1 2
c 1
```
Bizarre, les littéraux a et b n'apparaissent pas !

@olzd @FredMaris À l'aide ! Je ne suis pas certain de comprendre comment s'utilise cette fonction.  :confused:
