### ISSUE TITLE
Bug avec accents et espaces dans les noms de fichier (touistc sous windows)

### ISSUE THREAD

**Issue by maelvalais** [FredMaris/touist#135]
Avec la version 7fc8795, la commande envoyée par touist lors de l'appel de minisat pose un problème avec les accents ou les espaces. Il semble manquer les guillemets lors de l'appel...

    launch(): cmd executed: java -jar external\minisat.jar C:\Users\Maël Valais\Downloads\touist-v1.1-60-g7fc8795-windows-x64\out.cnf

retourne l'exception
```
Exception in thread "Thread-6" java.lang.NumberFormatException: For input string: "Error"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at solution.SolverTestSAT4J.parseModel(SolverTestSAT4J.java:179)
        at solution.SolverTestSAT4J.nextModel(SolverTestSAT4J.java:163)
        at solution.ModelListIterator.hasNext(ModelListIterator.java:59)
        at gui.editionView.ParentEditionPanel.initResultView(ParentEditionPanel.java:554)
        at gui.editionView.ParentEditionPanel.access$500(ParentEditionPanel.java:58)
        at gui.editionView.ParentEditionPanel$6.run(ParentEditionPanel.java:277)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by maelvalais** [comment]
Je viens de tester, y'a le même souci avec l'appel du solveur (mainenant la traduction fonctionne !). Faudra faire la même modif sur les appels du genre `Runtime.getRuntime().exec()`
